version: "3.8"

services:
  app:
    build: .
    container_name: app
    depends_on:
      - records_db
    ports:
      - target: 8080
        published: 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://records_db:5432/records_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  records_db:
    image: postgres
    container_name: records_db
    restart: always
    ports:
      - target: 5432
        published: 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=records_db