spring.application.name=back-end-lab-2
logging.level.org.springframework.security=DEBUG
logging.level.com.kovalenko.backendlab2=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/records_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mvc.hiddenmethod.filter.enabled=true

spring.app.jwtSecret=Hb7d++3tvUxn0qopTR3Nd0ZfZ5wfD0Zx5fofaPdSt0YOg9Rq0TN++pOEbfMci7Qf
spring.app.jwtExpirationMinutes=1440